-- 테이블 생성
CREATE TABLE public.menus (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name text NOT NULL,
  image_url text,
  price integer NOT NULL CHECK (price >= 0),
  is_hot boolean NOT NULL DEFAULT true,
  caffeine_mg integer DEFAULT 0,
  sugar_g integer DEFAULT 0,
  description text,
  aliases text[], -- 별명을 위한 배열 타입
  search_text text, -- 임베딩을 위한 텍스트
  embedding vector(1536) -- OpenAI ada-002 모델 기준 벡터
);

-- RLS 비활성화, 테스트용 public
ALTER TABLE public.menus ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users"
ON public.menus
FOR SELECT
USING (true);